#!/usr/bin/env php
<?php

/**
 * CLI executable for showgrabber application
 */

require __DIR__ . '/vendor/autoload.php';
$container = require __DIR__ . '/config/configure-services.php';
$container->get('console.application')->run();