services:

  console.application:
    class: Symfony\Component\Console\Application
    calls:
      - [addCommands, [[@console.commands.list-shows, @console.commands.list-episodes]]]

  console.application.tester:
    class: Symfony\Component\Console\Tester\ApplicationTester
    arguments: [@console.application]

  console.commands.list-shows:
    class: Piso\Console\Command\ListShowsCommand
    arguments: [list-shows, @index.shows]

  console.commands.list-episodes:
    class: Piso\Console\Command\ListEpisodesCommand
    arguments: [list-episodes, @index.episode]

  index.shows:
    class: Piso\Index\ShowsIndex\ConfigShowsIndex
    arguments: [@config.shows]

  index.episode:
    class: Piso\Index\EpisodeIndex\FilesystemEpisodeIndex
    arguments: [@config.shows]

  config.shows:
    class: Piso\Config\ShowsConfig\YamlShowsConfig
    arguments: [@configfile.yaml]

  configfile.yaml:
    class: Piso\Util\YamlReader
    arguments: [@symfony.yaml, %config.filename%]

  symfony.yaml:
    class: Symfony\Component\Yaml\Parser

parameters:

  config.filename: config.yml