services:

  console.application:
    class: Symfony\Component\Console\Application
    calls:
      - [addCommands, [[@console.commands.list-shows, @console.commands.list-episodes]]]

  console.application.tester:
    class: Symfony\Component\Console\Tester\ApplicationTester
    arguments: [@console.application]

  console.commands.list-shows:
    class: Piso\Console\Command\ListShowsCommand
    arguments: [list-shows, @shows.show-index]

  console.commands.list-episodes:
    class: Piso\Console\Command\ListEpisodesCommand
    arguments: [list-episodes]

  shows.show-index:
    class: Piso\Shows\ShowIndex\YamlShowIndex
    arguments: [@util.yaml, %config.filename%]

  util.yaml:
    class: Piso\Util\YamlReader
    arguments: [@symfony.yaml]

  symfony.yaml:
    class: Symfony\Component\Yaml\Parser

parameters:

  config.filename: config.yml